---
- name: Ensure Openldap Directories Exist
  when: inventory_hostname == groups['managers'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - /datavol/apps/openldap/data
    - /datavol/apps/openldap/config
  tags: openldap

- name: Create Openldap Docker Container
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: openldap
    image: "{{ openldap_docker_image }}:{{ openldap_version }}"
    hostname: "{{ openldap_hostname }}"
    networks:
      - "{{ traefik_network }}"
    publish:
      - published_port: "{{openldap_port}}"
        target_port: "{{openldap_port}}"
        protocol: "tcp"
        mode: "host"
      - published_port: "636"
        target_port: "636"
        protocol: "tcp"
        mode: "host"
    mode: replicated
    force_update: false
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == {{ docker_master1_node_id }}
    replicas: 1
    env:
      LDAP_ORGANISATION: "{{ openldap_organisation }}"
      LDAP_DOMAIN: "{{ openldap_domain }}"
      LDAP_ADMIN_PASSWORD: "{{ openldap_admin_password }}"
      LDAP_READONLY_USER: "true"
    mounts:
      - source: /datavol/apps/openldap/data/
        target: /var/lib/ldap
        type: bind
      - source: /datavol/apps/openldap/config/
        target: /etc/ldap/slapd.d
        type: bind
    state: present
  tags: openldap