---
- name: Ensure Geoip Directories Exist
  when: inventory_hostname == groups['workers'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_root_directory}}/geoip"
  tags: geoip

- name: Deploy Geoip Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: geoip
    hostname: "{{ geoip_hostname }}"
    image: "{{ geoip_docker_image }}:{{ geoip_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: false
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == {{ docker_worker1_node_id }}
    env:
      GEOIPUPDATE_EDITION_IDS: "GeoLite2-City GeoLite2-ASN"
      GEOIPUPDATE_FREQUENCY: "8"
      GEOIPUPDATE_ACCOUNT_ID: "{geoip_account_id}"
      GEOIPUPDATE_LICENSE_KEY: "{geoip_license_key}"
    replicas: 1
    mounts:
      - source: "{{project_root_directory}}/geoip/"
        target: /usr/share/GeoIP
        type: bind
    state: present
  tags: geoip