---
- name: Deploy Exportarr Prowlarr Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: exportarr_prowlarr
    hostname: "{{exportarr_prowlarr_hostname}}"
    image: "{{exportarr_docker_image}}:{{exportarr_version}}"
    args: "prowlarr"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: false
    restart_config:
      condition: on-failure
    env:
      PORT: "9710"
      URL: "http://prowlarr:9696"
      APIKEY: "cfced2e2cc704d1badf4cb99eba3acc7"
      ENABLE_ADDITIONAL_METRICS: "TRUE"
    placement:
      constraints:
        - node.id == {{docker_worker1_node_id}}
    replicas: 1
    state: present
  tags: exportarr

- import_tasks: "{{role_path}}/tasks/lidarr.yml"
  tags:
    - exportarr

- import_tasks: "{{role_path}}/tasks/radarr.yml"
  tags:
    - exportarr

- import_tasks: "{{role_path}}/tasks/sabnzbd.yml"
  tags:
    - exportarr

- import_tasks: "{{role_path}}/tasks/sonarr.yml"
  tags:
    - exportarr

- import_tasks: "{{role_path}}/tasks/readarr.yml"
  tags:
    - exportarr
  