---
- name: Ensure Media Download Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_download_directory}}/firefox"
  tags: firefox

- name: Ensure Firefox Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /datavol/apps/firefox2
    - /datavol/apps/firefox2/config
  tags: firefox

- name: Create Firefox Docker Compose File
  when: inventory_hostname == groups['managers'][0]
  template:
    src: docker-compose.yml.j2
    dest: "{{project_root_directory}}/firefox2/docker-compose.yml"
    mode: 0775
  tags: firefox

- name: Deploy Firefox from Compose File
  when: inventory_hostname == groups['managers'][0]
  docker_stack:
    state: present
    name: firefox
    compose:
      - "{{project_root_directory}}/firefox2/docker-compose.yml"
  tags: firefox