---
- name: Ensure Media Download Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_download_directory}}/firefox"
  tags: firefox

- name: Ensure Firefox Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /datavol/apps/firefox
  tags: firefox

- name: Deploy Firefox
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: firefox
    hostname: "{{ firefox_hostname }}.{{ project_tld }}"
    image: "{{ firefox_docker_image }}:{{ firefox_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: false
    restart_config:
      condition: on-failure
    env:
      TZ: "{{ default_timezone }}"
      USER_ID: "{{ default_puid }}"
      GROUP_ID: "{{ default_pgid }}"
      FF_OPEN_URL: "https://ipinfo.io/what-is-my-ip"
      FF_PREF_DOWNLOAD_DIR: "browser.download.dir=/media/downloads/firefox"
      FF_PREF_HTTP_PROXY: "network.proxy.http=transmission"
      FF_PREF_HTTP_PROXY_PORT: "network.proxy.http_port=8118"
      FF_PREF_SSL_PROXY: "network.proxy.http=transmission"
      FF_PREF_SSL_PROXY_PORT: "network.proxy.http_port=8118"
      FF_PREF_PROXY_TYPE: "network.proxy.type=1"
    placement:
      constraints:
        - node.id == {{ docker_worker1_node_id }}
    replicas: 1
    mounts:
      - source: firefox
        target: /config
        type: volume
      - source: "{{project_download_directory}}"
        target: /media/downloads
        type: bind
    labels:
      traefik.http.routers.firefox.entrypoints: "websecure"
      traefik.http.routers.firefox.rule: "Host(`firefox.{{project_tld}}`)"
      # traefik.http.middlewares.firefox-prefix.addPrefix.prefix: "/"
      traefik.http.routers.firefox.middlewares: "authelia@file"
      traefik.http.routers.firefox.tls: "true"
      traefik.http.routers.firefox.service: "firefox"
      # traefik.http.routers.firefox.tls.certresolver: "{{default_certificate_resolver}}" # Un-Comment this line to use a rule-based cert
      traefik.http.services.firefox.loadbalancer.server.port: "{{firefox_port}}"
      traefik.enable: "true"
    state: present
  tags: firefox