---
- name: Ensure Plexmm Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ project_root_directory }}/plexmm"
    - "{{ project_root_directory }}/plexmm/assets"
  tags: plexmm

- name: Ensure Plexmm Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: config.yml.j2
    dest: "{{ project_root_directory }}/plexmm/config.yml"
    mode: 0755
  tags: plexmm
  no_log: false

- name: Deploy Plexmm Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: plexmm
    hostname: "{{plexmm_hostname}}"
    image: "{{plexmm_docker_image}}:{{plexmm_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: true
    restart_config:
      condition: on-failure
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      TZ: "{{default_timezone}}"
      PMM_CONFIG: "/config/config.yml"
      PMM_TIME: "03:00"
      PMM_RUN: "True"
      PMM_TEST: "False"
      PMM_NO_MISSING: "False"
    placement:
      constraints:
        - node.id == {{docker_worker1_node_id}}
    replicas: 1
    mounts:
      - source: "{{project_root_directory}}/plexmm/"
        target: /config
        type: bind
    state: present
  tags: plexmm
  