---
- name: Deploy Core Services
  hosts: all
  gather_facts: false
  become: true
  roles:
    # - kutt
    # - wallabag
    # - freshrss
    # - xbrowsersync
    # - cyberchef
    # - omada
    - guacamole
    # - paperless
    # - plausible
    # - listmonk
    - wiki.js
    # - mkdocs
    - graylog
    - adminer
    - phpmyadmin
    - phpldapadmin
    - ldap-user-manager
    - unifi-controller
    - graphite
    - prometheus
    - influxdb
    - telegraf
    - grafana
    - speedtest
    - auto-mb4
    - firefox
    - rustdesk
    - meshcentral
