---
- name: Deploy Media Services
  hosts: all
  gather_facts: true
  become: false
  roles:
    - transmission
    - sabnzbd
    # - qbittorrent
    - prowlarr
    - sonarr
    - radarr
    - lidarr
    - readarr
    # - bazarr
    # - kavita
    # - ombi
    # - plex
    # - photoprism
    # - immich
    # - peertube
    # - tautulli
    # - wizarr
    # - tdarr
    # - unpackerr
    