---
- name: Ensure Gluetun Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_root_directory}}/gluetun"
    state: directory
  tags: gluetun

- name: Create Gluetun Docker Compose File
  when: inventory_hostname == groups['media'][0]
  template:
    src: docker-compose.yml.j2
    dest: "{{project_root_directory}}/gluetun/docker-compose.yml"
    mode: 0775
  tags: gluetun

- name: Deploy Gluetun from Compose File
  when: inventory_hostname == groups['media'][0]
  docker_stack:
    state: present
    name: gluetun
    compose:
      - "{{project_root_directory}}/gluetun/docker-compose.yml"
  tags: gluetun