---
authelia_database: "{{ vault_authelia_database }}"
authelia_database_user: "{{ vault_authelia_database_user }}"
authelia_database_password: "{{ vault_authelia_database_password }}"
authelia_duo_hostname: "{{ vault_authelia_duo_hostname }}"
authelia_duo_integration_key: "{{ vault_authelia_duo_integration_key }}"
authelia_duo_secret_key: "{{ vault_authelia_duo_secret_key }}"
authelia_encryption_key: "{{ vault_authelia_encryption_key }}"
authelia_ldap_base_dn: "{{ vault_authelia_ldap_base_dn }}"
authelia_ldap_password: "{{ vault_authelia_ldap_password }}"
authelia_ldap_url: "{{ vault_authelia_ldap_url }}"
authelia_ldap_user: "{{ vault_authelia_ldap_user }}"
authelia_notifier_sender: "{{ vault_authelia_notifier_sender }}"
authelia_notifier_startup_check_address: "{{ vault_authelia_notifier_startup_check_address }}"
authelia_oauth_portainer_clientid: "{{ vault_authelia_oauth_portainer_clientid }}"
authelia_oauth_portainer_secret: "{{ vault_authelia_oauth_portainer_secret }}"
authelia_jwt_secret: "{{ vault_authelia_jwt_secret }}"
authelia_session_secret: "{{ vault_authelia_session_secret }}"
authelia_user_1_username: "{{ vault_authelia_user_1_username }}"
authelia_user_1_display_name: "{{ vault_authelia_user_1_display_name }}"
authelia_user_1_password: "{{ vault_authelia_user_1_password }}"
authelia_user_1_email: "{{ vault_authelia_user_1_email }}"
authelia_user_2_username: "{{ vault_authelia_user_2_username }}"
authelia_user_2_display_name: "{{ vault_authelia_user_2_display_name }}"
authelia_user_2_password: "{{ vault_authelia_user_2_password }}"
authelia_user_2_email: "{{ vault_authelia_user_2_email }}"
