---
- name: Ensure Readarr Audiobooks Media Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_media_directory}}/Audiobooks"
    state: directory
  tags: readarr

- name: Ensure Readarr Audiobooks Media Download Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_download_directory}}/audiobooks"
    state: directory
  tags: readarr

- name: Ensure Readarr Audiobooks Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_root_directory}}/readarr2"
    state: directory
  tags: readarr

- name: Ensure Readarr Audiobooks Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_root_directory}}/readarr2"
    - "{{project_root_directory}}/readarr2/config"
    - "{{project_root_directory}}/readarr2/custom-services"
    - "{{project_root_directory}}/readarr2/custom-cont-init"
  tags: readarr

- name: Ensure Readarr Audiobooks Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: config-audiobooks.xml.j2
    dest: "{{project_root_directory}}/readarr2/config/config.xml"
  tags: readarr
  no_log: true

- name: Ensure Readarr Audiobooks Extended Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: extended.conf.j2
    dest: "{{project_root_directory}}/readarr2/config/extended.conf"
  tags: readarr
  no_log: true

- name: Ensure Readarr Audiobooks custom-services Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: scripts_init.bash.j2
    dest: "{{project_root_directory}}/readarr2/custom-cont-init/scripts_init.bash"
  tags: readarr
  no_log: true

- name: Deploy Readarr Audiobooks Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: readarr_audiobooks
    hostname: "{{readarr_audiobooks_hostname}}"
    image: "{{readarr_audiobooks_docker_image}}:{{readarr_audiobooks_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: false
    restart_config:
      condition: on-failure
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      TZ: "{{default_timezone}}"
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:{{readarr_hostname}}"
      TP_THEME: "{{theme_park_default}}"
    placement:
      constraints:
        - node.id == {{docker_worker2_node_id}}
    replicas: 1
    mounts:
      - source: "{{project_root_directory}}/readarr2/config/"
        target: /config
        type: bind
      - source: "{{project_root_directory}}/readarr2/custom-services/"
        target: /custom-services.d
        type: bind
      - source: "{{project_root_directory}}/readarr2/custom-cont-init/"
        target: /custom-cont-init.d
        type: bind
      - source: "{{project_media_directory}}/Audiobooks/"
        target: /media/audiobooks
        type: bind
      - source: "{{project_download_directory}}"
        target: /media/downloads
        type: bind
    labels:
      traefik.http.routers.readarraudio.entrypoints: "websecure"
      traefik.http.routers.readarraudio.rule: "Host(`readarraudio.{{project_tld}}`)"
      traefik.http.routers.readarraudio.middlewares: "default-headers@file,authelia@file"
      traefik.http.routers.readarraudio.tls: "true"
      traefik.http.routers.readarraudio.service: "readarraudio"
      # traefik.http.routers.readarraudio.tls.certresolver: "{{default_certificate_resolver}}" # Un-Comment this line to use a rule-based cert
      traefik.http.services.readarraudio.loadbalancer.server.port: "{{readarr_audiobooks_port}}"
      traefik.enable: "true"
    state: present
  tags: readarr
