---
- name: Ensure Media Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_media_directory}}/Music"
    - "{{project_media_directory}}/Playlists"
    - "{{project_media_directory}}/Podcasts"
  tags: airsonic

- name: Ensure Airsonic Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_root_directory}}/airsonic"
    state: directory
  tags: airsonic

- name: Deploy Airsonic Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: airsonic
    hostname: "{{airsonic_hostname}}"
    image: "{{airsonic_docker_image}}:{{airsonic_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: true
    restart_config:
      condition: on-failure
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      TZ: "{{default_timezone}}"
    placement:
      constraints:
        - node.id == {{docker_worker2_node_id}}
    replicas: 1
    mounts:
      - source: "{{project_root_directory}}/airsonic/"
        target: /config
        type: bind
      - source: "{{project_media_directory}}/Music/"
        target: /music
        type: bind
      - source: "{{project_media_directory}}/Playlists/"
        target: /playlists
        type: bind
      - source: "{{project_media_directory}}/Podcasts/"
        target: /podcasts
        type: bind
    labels:
      traefik.http.routers.airsonic.entrypoints: "websecure"
      traefik.http.routers.airsonic.rule: "Host(`airsonic.{{project_tld}}`)"
      traefik.http.routers.airsonic.middlewares: "default-headers@file"
      traefik.http.routers.airsonic.tls: "true"
      traefik.http.routers.airsonic.service: "airsonic"
      # traefik.http.routers.airsonic.tls.certresolver: "{{default_certificate_resolver}}" # Un-Comment this line to use a rule-based cert
      traefik.http.services.airsonic.loadbalancer.server.port: "{{airsonic_port}}"
      traefik.enable: "true"
    state: present
  tags: airsonic