---
- name: Ensure phpmyadmin Dataset Exist
  when: inventory_hostname == groups['workers'][0]
  file:
    name: "{{project_root_directory}}/phpmyadmin"
    state: directory
  tags: phpmyadmin

- name: Deploy phpmyadmin Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: phpmyadmin
    hostname: "{{ phpmyadmin_hostname }}"
    image: "{{ phpmyadmin_docker_image }}:{{ phpmyadmin_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: true
    restart_config:
      condition: on-failure
    env:
      PMA_ARBITRARY: "0"
      PMA_HOSTS: "{{ phpmyadmin_hosts }}"
      PMA_USER: "{{ phpmyadmin_user }}"
      PMA_PASSWORD: "{{ phpmyadmin_password }}"
      PMA_ABSOLUTE_URI: "https://{{home_tld}}/phpmyadmin/"
      # PMA_PMADB: "phpmyadmin"
      # PMA_CONTROLUSER: "{{ phpmyadmin_controluser }}"
      # PMA_CONTROLPASS: "{{ phpmyadmin_controlpass }}"
      # PMA_QUERYHISTORYDB: "true"
    placement:
      constraints:
        - node.id == {{ docker_worker1_node_id }}
    replicas: 1
    mounts:
      - source: "{{project_root_directory}}/phpmyadmin/"
        target: /config
        type: bind
    labels:
      traefik.http.routers.phpmyadmin.entrypoints: "websecure"
      traefik.http.routers.phpmyadmin.rule: "HostHeader(`{{home_tld}}`) && PathPrefix(`/phpmyadmin`)"
      traefik.http.routers.phpmyadmin.middlewares: "default-headers@file,authelia@file"
      traefik.http.routers.phpmyadmin.tls: "true"
      traefik.http.routers.phpmyadmin.service: "phpmyadmin"
      # traefik.http.routers.phpmyadmin.tls.certresolver: "{{default_certificate_resolver}}" # Un-Comment this line to use a rule-based cert
      traefik.http.services.phpmyadmin.loadbalancer.server.port: "{{phpmyadmin_port}}"
      traefik.enable: "true"
    state: present
  tags: phpmyadmin