---
- name: Ensure Media Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_media_directory}}/Videos"
    state: directory
  tags: radarr

- name: Ensure Media Download Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_download_directory}}"
    state: directory
  tags: radarr

- name: Ensure Radarr Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_newroot_directory}}/radarr4k"
    - "{{project_newroot_directory}}/radarr4k/config"
    - "{{project_newroot_directory}}/radarr4k/custom-services"
    - "{{project_newroot_directory}}/radarr4k/custom-cont-init"
  tags: radarr

- name: Ensure Radarr Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: config4k.xml.j2
    dest: "{{project_newroot_directory}}/radarr4k/config/config.xml"
  tags: radarr
  no_log: true

- name: Ensure Radarr Extended Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: extended.conf.j2
    dest: "{{project_newroot_directory}}/radarr4k/config/extended.conf"
  tags: radarr
  no_log: true

- name: Ensure Radarr Main Database exist
  ansible.builtin.import_tasks: roles/postgres/tasks/database_manager.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    database_name: "{{ radarr_maindb_database }}4k"
    database_user: "{{ radarr_database_user }}"
    database_password: "{{ radarr_database_password }}"
  tags: radarr
  no_log: true

- name: Ensure Radarr Log Database exist
  ansible.builtin.import_tasks: roles/postgres/tasks/database_manager.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    database_name: "{{ radarr_logdb_database }}4k"
    database_user: "{{ radarr_database_user }}"
    database_password: "{{ radarr_database_password }}"
  tags: radarr
  no_log: true

- name: Ensure Radarr custom-services Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: scripts_init.bash.j2
    dest: "{{project_newroot_directory}}/radarr4k/custom-cont-init/scripts_init.bash"
  tags: radarr
  no_log: true

- name: Deploy Radarr Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: radarr4k
    hostname: "{{radarr_hostname}}4k"
    image: "{{radarr_docker_image}}:{{radarr_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: false
    restart_config:
      condition: on-failure
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      TZ: "{{default_timezone}}"
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:{{radarr_hostname}}"
      TP_THEME: "{{theme_park_default}}"
    placement:
      constraints:
        - node.id == {{docker_worker2_node_id}}
    replicas: 1
    mounts:
      - source: "{{project_newroot_directory}}/radarr4k/config/"
        target: /config
        type: bind
      - source: "{{project_newroot_directory}}/radarr4k/custom-services/"
        target: /custom-services.d
        type: bind
      - source: "{{project_newroot_directory}}/radarr4k/custom-cont-init/"
        target: /custom-cont-init.d
        type: bind
      - source: "{{project_media_directory}}/Videos/"
        target: /media/movies
        type: bind
      - source: "{{project_download_directory}}"
        target: /media/downloads
        type: bind
    labels:
      traefik.http.routers.radarr4k.entrypoints: "websecure"
      traefik.http.routers.radarr4k.rule: "Host(`radarr4k.{{project_tld}}`)"
      traefik.http.routers.radarr4k.middlewares: "default-headers@file,authentik@file"
      traefik.http.routers.radarr4k.tls: "true"
      traefik.http.routers.radarr4k.service: "radarr4k"
      # traefik.http.routers.radarr4k.tls.certresolver: "{{default_certificate_resolver}}" # Un-Comment this line to use a rule-based cert
      traefik.http.services.radarr4k.loadbalancer.server.port: "{{radarr_port}}"
      traefik.enable: "true"
    state: present
  tags: radarr
  