---
- name: Ensure Homepage Directories Exist
  when: inventory_hostname == groups['managers'][0]
  ansible.builtin.file:
    name: "{{ project_root_directory }}/homepage"
    state: directory
    mode: '0755'
  tags: homepage

# - name: Ensure Homepage Configuration Files Exist
#   when: inventory_hostname == groups['managers'][0]
#   ansible.builtin.template:
#     src: config.yml.j2
#     dest: "{{ project_root_directory }}/homepage/config.yml"
#     mode: '0755'
#   tags: homepage
#   no_log: true

- name: Deploy Homepage Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: homepage
    hostname: "{{ homepage_hostname }}"
    image: "{{ homepage_docker_image }}:{{ homepage_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: global
    env:
      PUID: "{{ media_user }}"
      PGID: "{{ media_group }}"
      HOMEPAGE_ALLOWED_HOSTS: "www.{{ project_tld }}"
    restart_config:
      condition: on-failure
    placement:
      constraints:
        - node.id == {{ docker_master1_node_id }}
    mounts:
      - source: "{{ project_root_directory }}/homepage"
        target: /app/config
        type: bind
    labels:
      traefik.http.routers.homepage.entrypoints: "websecure"
      traefik.http.routers.homepage.rule: "Host(`www.{{ project_tld }}`) || Host(`{{ project_tld }}`)"
      traefik.http.routers.homepage.middlewares: "default-headers@file,authelia@file"
      traefik.http.routers.homepage.tls: "true"
      traefik.http.routers.homepage.service: "homepage"
      # traefik.http.routers.homepage.tls.certresolver: "{{ default_certificate_resolver }}" # Un-Comment this line to use a rule-based cert
      traefik.http.services.homepage.loadbalancer.server.port: "{{ homepage_port }}"
      traefik.enable: "true"
    state: present
  tags: homepage
