---
- name: Ensure Media Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /media/Audiobooks/
    - /media/Books/
    - /media/Comics/
    - /media/Music/
    - /media/Music Videos/
    - /media/Photos/
    - /media/Playlists/
    - /media/Podcasts/
    - /media/Videos/
    - /media/Videos/Anime Movies/
    - /media/Videos/Anime TV/
    - /media/Videos/Fitness/
    - /media/Videos/Kids Movies/
    - /media/Videos/Kids TV Series/
    - /media/Videos/Miscellaneous/
    - /media/Videos/Movies/
    - /media/Videos/TV Series/
  tags: transmission

- name: Ensure Media Download Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /media/Downloads
    - /media/Downloads/incomplete
    - /media/Downloads/anime
    - /media/Downloads/audiobooks
    - /media/Downloads/books
    - /media/Downloads/comics
    - /media/Downloads/kids
    - /media/Downloads/movies
    - /media/Downloads/music
    - /media/Downloads/tv
  tags: transmission

- name: Ensure Transmission Watch Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: /media/Watch/torrentfiles
    state: directory
  tags: transmission

- name: Ensure Transmission Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /datavol/apps/transmission
    - /datavol/apps/transmission/config
    - /datavol/apps/transmission/data
  tags: transmission

- name: Create Transmission Docker Compose File
  when: inventory_hostname == groups['managers'][0]
  template:
    src: docker-compose.yml.j2
    dest: "{{project_root_directory}}/transmission/docker-compose.yml"
    mode: 0775
  tags: transmission

- name: Deploy Transmission from Compose File
  when: inventory_hostname == groups['managers'][0]
  docker_stack:
    state: present
    name: transmission
    compose:
      - "{{project_root_directory}}/transmission/docker-compose.yml"
  tags: transmission
   