---
- name: Ensure Media Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_media_directory}}/Audiobooks"
    - "{{project_media_directory}}/Books"
    - "{{project_media_directory}}/Comics"
    - "{{project_media_directory}}/Music"
    - "{{project_media_directory}}/Music Videos"
    - "{{project_media_directory}}/Photos"
    - "{{project_media_directory}}/Playlists"
    - "{{project_media_directory}}/Podcasts"
    - "{{project_media_directory}}/Videos"
    - "{{project_media_directory}}/Videos/Anime TV"
    - "{{project_media_directory}}/Videos/Fitness"
    - "{{project_media_directory}}/Videos/Miscellaneous"
    - "{{project_media_directory}}/Videos/Movies"
    - "{{project_media_directory}}/Videos/TV Series"
  tags: qbittorrent

- name: Ensure Media Download Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_media_directory}}/Downloads"
    - "{{project_media_directory}}/Downloads/incomplete"
    - "{{project_media_directory}}/Downloads/anime"
    - "{{project_media_directory}}/Downloads/audiobooks"
    - "{{project_media_directory}}/Downloads/books"
    - "{{project_media_directory}}/Downloads/comics"
    - "{{project_media_directory}}/Downloads/kids"
    - "{{project_media_directory}}/Downloads/movies"
    - "{{project_media_directory}}/Downloads/music"
    - "{{project_media_directory}}/Downloads/tv"
  tags: qbittorrent

- name: Ensure qBittorrent Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_root_directory}}/qbittorrent"
    state: directory
  tags: qbittorrent

- name: Ensure Gluetun Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_root_directory}}/gluetun"
    state: directory
  tags: gluetun

- name: Create qBittorrent Docker Compose File
  when: inventory_hostname == groups['managers'][0]
  template:
    src: docker-compose.yml.j2
    dest: "{{project_root_directory}}/qbittorrent/docker-compose.yml"
    mode: 0775
  tags: qbittorrent

- name: Deploy qBittorrent from Compose File
  when: inventory_hostname == groups['managers'][0]
  docker_stack:
    state: present
    name: qbittorrent
    compose:
      - "{{project_root_directory}}/qbittorrent/docker-compose.yml"
  tags: qbittorrent