---
- name: Deploy Docker-GC Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: dockergc
    hostname: "{{ dockergc_hostname }}"
    image: "{{ dockergc_docker_image }}:{{ dockergc_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: global
    force_update: false
    restart_config:
      condition: on-failure
    env:
      CRON: "0 0 * * 7" # Every Sunday at 1am
      FORCE_IMAGE_REMOVAL: "1"
      FORCE_CONTAINER_REMOVAL: "0"
      GRACE_PERIOD_SECONDS: "604800"
      DRY_RUN: "0"
      TZ: "{{ default_timezone }}"
      DOCKER_HOST: "tcp://{{ '{{' }} .Node.Hostname {{ '}}' }}-socketproxy:2375"
    placement:
      constraints:
        - node.platform.os == linux
    replicas: 1
    state: present
  tags: dockergc
  