---
gluetun_openvpn_countries: "Switzerland,Mexico"
gluetun_openvpn_password: "{{ vault_expressvpn_password }}"
gluetun_openvpn_username: "{{ vault_expressvpn_username }}"
gluetun_qbittorrent_port: "8080"
