---
- name: Ensure Socket Proxy Dataset Exist
  when: inventory_hostname == groups['managers'][0]
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /datavol/apps/socket-proxy
  tags: socket-proxy

- name: Create Socket Proxy Docker Compose File
  when: inventory_hostname == groups['managers'][0]
  template:
    src: docker-compose.yml.j2
    dest: "{{project_root_directory}}/socket-proxy/docker-compose.yml"
    mode: 0775
  tags: socket-proxy

- name: Deploy Socket Proxy from Compose File
  when: inventory_hostname == groups['managers'][0]
  docker_stack:
    state: present
    name: socket-proxy
    compose:
      - "{{project_root_directory}}/socket-proxy/docker-compose.yml"
  tags: socket-proxy
