---
- name: Ensure Media Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_media_directory}}/Videos"
    state: directory
  tags: sonarr

- name: Ensure Media Download Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_download_directory}}"
    state: directory
  tags: sonarr

- name: Ensure Sonarr Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_root_directory}}/sonarr4k"
    - "{{project_root_directory}}/sonarr4k/config"
    - "{{project_root_directory}}/sonarr4k/custom-services"
    - "{{project_root_directory}}/sonarr4k/custom-cont-init"
  tags: sonarr

- name: Ensure Sonarr Main Database exist
  ansible.builtin.import_tasks: roles/postgres/tasks/database_manager.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    database_name: "{{ sonarr_maindb_database }}4k"
    database_user: "{{ sonarr_database_user }}"
    database_password: "{{ sonarr_database_password }}"
  tags: sonarr
  no_log: true

- name: Ensure Sonarr Log Database exist
  ansible.builtin.import_tasks: roles/postgres/tasks/database_manager.yml
  when: inventory_hostname == groups['managers'][0]
  vars:
    database_name: "{{ sonarr_logdb_database }}4k"
    database_user: "{{ sonarr_database_user }}"
    database_password: "{{ sonarr_database_password }}"
  tags: sonarr
  no_log: true
  
- name: Ensure Sonarr Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: config4k.xml.j2
    dest: "{{project_root_directory}}/sonarr4k/config/config.xml"
  tags: sonarr
  no_log: true

- name: Ensure Sonarr Extended Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: extended.conf.j2
    dest: "{{project_root_directory}}/sonarr4k/config/extended.conf"
  tags: sonarr
  no_log: true

- name: Ensure Sonarr custom-services Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: scripts_init.bash.j2
    dest: "{{project_root_directory}}/sonarr4k/custom-cont-init/scripts_init.bash"
  tags: sonarr
  no_log: true

- name: Deploy Sonarr Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: sonarr4k
    hostname: "{{sonarr_hostname}}4k"
    image: "{{sonarr_docker_image}}:{{sonarr_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: false
    restart_config:
      condition: on-failure
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      TZ: "{{default_timezone}}"
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:{{sonarr_hostname}}"
      TP_THEME: "{{theme_park_default}}"
    placement:
      constraints:
        - node.id == {{docker_worker2_node_id}}
    replicas: 1
    mounts:
      - source: "{{project_root_directory}}/sonarr4k/config/"
        target: /config/
        type: bind
      - source: "{{project_root_directory}}/sonarr4k/custom-services/"
        target: /custom-services.d
        type: bind
      - source: "{{project_root_directory}}/sonarr4k/custom-cont-init/"
        target: /custom-cont-init.d
        type: bind
      - source: "{{project_media_directory}}/Videos/"
        target: /media/tv/
        type: bind
      - source: "{{project_download_directory}}"
        target: /media/downloads/
        type: bind
    labels:
      traefik.http.routers.sonarr4k.entrypoints: "websecure"
      traefik.http.routers.sonarr4k.rule: "Host(`sonarr4k.{{project_tld}}`)"
      traefik.http.routers.sonarr4k.middlewares: "default-headers@file,authentik@file"
      traefik.http.routers.sonarr4k.tls: "true"
      traefik.http.routers.sonarr4k.service: "sonarr4k"
      # traefik.http.routers.sonarr4k.tls.certresolver: "{{default_certificate_resolver}}" # Un-Comment this line to use a rule-based cert
      traefik.http.services.sonarr4k.loadbalancer.server.port: "{{sonarr_port}}"
      traefik.enable: "true"
    state: present
  tags: sonarr
