---
- name: Ensure Media Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{ item }}"
    state: directory
  loop:
    - /media/Videos/
    - /media/Videos/Anime Movies/
    - /media/Videos/Anime TV/
    - /media/Videos/Fitness/
    - /media/Videos/Kids Movies/
    - /media/Videos/Kids TV Series/
    - /media/Videos/Miscellaneous/
    - /media/Videos/Movies/
    - /media/Videos/TV Series/
  tags: bazarr

- name: Ensure Bazarr Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{ project_root_directory }}/bazarr"
    state: directory
  tags: bazarr

- name: Ensure Bazarr Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: config.ini.j2
    mode: 0644
    dest: "{{ project_root_directory }}/bazarr/config/config.ini"
  tags: bazarr
  no_log: true

- name: Deploy Bazarr Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: bazarr
    hostname: "{{ bazarr_hostname }}"
    image: "{{ bazarr_docker_image }}:{{ bazarr_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: true
    restart_config:
      condition: on-failure
    env:
      PUID: "{{ media_user }}"
      PGID: "{{ media_group }}"
      TZ: "{{ default_timezone }}"
      DOCKER_MODS: "gilbn/theme.park:{{ bazarr_hostname }}"
      TP_THEME: "{{ theme_park_default }}"
    placement:
      constraints:
        - node.id == {{ docker_worker2_node_id }}
    replicas: 1
    mounts:
      - source: "{{ project_root_directory }}/bazarr/"
        target: /config/
        type: bind
      - source: "{{ project_media_directory }}/Videos/Movies/"
        target: /media/movies/
        type: bind
      - source: "{{ project_media_directory }}/Videos/TV Series/"
        target: /media/tv/
        type: bind
      - source: "{{ project_media_directory }}/Videos/Kids Movies/"
        target: /media/kids/
        type: bind
      - source: "{{ project_media_directory }}/Videos/Kids TV Series/"
        target: /media/kids_tv/
        type: bind
      - source: "{{ project_media_directory }}/Videos/Anime Movies/"
        target: /media/anime/
        type: bind
      - source: "{{ project_media_directory }}/Videos/Anime TV/"
        target: /media/anime_tv/
        type: bind
    labels:
      traefik.http.routers.bazarr.entrypoints: "websecure"
      traefik.http.routers.bazarr.rule: "Host(`bazarr.{{ project_tld }}`)"
      traefik.http.middlewares.bazarr_plausible.plugin.rewritebody.rewrites.regex: "</head>"
      traefik.http.middlewares.bazarr_plausible.plugin.rewritebody.rewrites.replacement: "<script defer data-domain='bazarr.{{ project_tld }}' src='https://plausible.{{ project_tld }}/js/plausible.js'></script></head>"
      traefik.http.routers.bazarr.middlewares: "default-headers@file,authelia@file,bazarr_plausible"
      traefik.http.routers.bazarr.tls: "true"
      traefik.http.routers.bazarr.service: "bazarr"
      # traefik.http.routers.bazarr.tls.certresolver: "{{ default_certificate_resolver }}" # Un-Comment this line to use a rule-based certs
      traefik.http.services.bazarr.loadbalancer.server.port: "{{ bazarr_port }}"
      traefik.enable: "true"
    state: present
  tags: bazarr