---
- name: Ensure Traefik Certdumper Dataset Exist
  when: inventory_hostname == groups['managers'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{project_root_directory}}/traefik"
    - "{{project_root_directory}}/traefik/letsencrypt"
    - "{{project_media_directory}}/Certs"
  tags: traefik_certdumper

- name: Deploy Traefik Certdumper Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: traefik_certdumper
    hostname: "{{ traefik_certdumper_hostname }}"
    image: "{{ traefik_certdumper_docker_image }}:{{ traefik_certdumper_version }}"
    networks:
      - "{{ traefik_network }}"
    mode: replicated
    force_update: false
    restart_config:
      condition: on-failure
    env:
      PKCS12_PASSWORD: "{{ traefik_certdumper_password }}"
      COMBINE_PKCS12: "yes"
      OVERRIDE_UID: "1000"
      OVERRIDE_GID: "1000"
      CONVERT_KEYS_TO_RSA: "yes"
    placement:
      constraints:
        - node.id == {{ docker_master1_node_id }}
    mounts:
      - source: "{{project_root_directory}}/traefik/letsencrypt/"
        target: /traefik
        type: bind
        readonly: true
      - source: "{{project_media_directory}}/Certs/"
        target: /output
        type: bind
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    replicas: 1
    state: present
  tags: traefik_certdumper
  