---
- name: Ensure Media Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - /media/Audiobooks/
    - /media/Books/
    - /media/Comics/
    - /media/Music/
    - /media/Music Videos/
    - /media/Photos/
    - /media/Playlists/
    - /media/Podcasts/
    - /media/Videos/
    - /media/Videos/Anime Movies/
    - /media/Videos/Anime TV/
    - /media/Videos/Fitness/
    - /media/Videos/Kids Movies/
    - /media/Videos/Kids TV Series/
    - /media/Videos/Miscellaneous/
    - /media/Videos/Movies/
    - /media/Videos/TV Series/
  tags: sabnzbd

- name: Ensure Media Download Datasets Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: "{{item}}"
    state: directory
  loop:
    - /media/Downloads
    - /media/Downloads/incomplete
    - /media/Downloads/anime
    - /media/Downloads/audiobooks
    - /media/Downloads/books
    - /media/Downloads/comics
    - /media/Downloads/kids
    - /media/Downloads/movies
    - /media/Downloads/music
    - /media/Downloads/tv
  tags: sabnzbd

- name: Ensure Sabnzbd Watch Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    path: /media/Watch/nzbfiles
    state: directory
  tags: sabnzbd

- name: Ensure Sabnzbd Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_root_directory}}/sabnzbd"
    state: directory
  tags: sabnzbd

- name: Ensure Sabnzbd Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: sabnzbd.ini.j2
    dest: "{{project_root_directory}}/sabnzbd/sabnzbd.ini"
  tags: sabnzbd
  no_log: true

- name: Deploy Sabnzbd Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: sabnzbd
    hostname: "{{sabnzbd_hostname}}"
    image: "{{sabnzbd_docker_image}}:{{sabnzbd_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: false
    restart_config:
      condition: on-failure
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      TZ: "{{default_timezone}}"
      DOCKER_MODS: "gilbn/theme.park:sabnzbd"
      TP_THEME: "{{theme_park_default}}"
    placement:
      constraints:
        - node.id == {{docker_worker2_node_id}}
    replicas: 1
    mounts:
      - source: "{{project_root_directory}}/sabnzbd/"
        target: /config
        type: bind
      - source: "{{project_download_directory}}/"
        target: /media/downloads
        type: bind
      - source: "{{project_media_directory}}/Watch/nzbfiles/"
        target: /media/watch
        type: bind
    labels:
      traefik.http.routers.sabnzbd.entrypoints: "websecure"
      traefik.http.routers.sabnzbd.rule: "Host(`sabnzbd.{{project_tld}}`)"
      traefik.http.routers.sabnzbd.middlewares: "default-headers@file,authelia@file"
      traefik.http.routers.sabnzbd.tls: "true"
      traefik.http.routers.sabnzbd.service: "sabnzbd"
      # traefik.http.routers.sabnzbd.tls.certresolver: "{{default_certificate_resolver}}" # Un-Comment this line to use a rule-based cert
      traefik.http.services.sabnzbd.loadbalancer.server.port: "{{sabnzbd_port}}"
      traefik.enable: "true"
    state: present
  tags: sabnzbd