---
- name: Ensure Media Datasets Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: "{{item}}"
    state: present
  loop:
    - docker2/media
    - docker2/media/anime
    - docker2/media/audiobooks
    - docker2/media/books
    - docker2/media/comics
    - docker2/media/kids
    - docker2/media/movies
    - docker2/media/music
    - docker2/media/tv
  tags: sabnzbd

- name: Ensure Media Download Datasets Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: "{{item}}"
    state: present
  loop:
    - docker2/media/downloads
    - docker2/media/downloads/incomplete
    - docker2/media/downloads/anime
    - docker2/media/downloads/audiobooks
    - docker2/media/downloads/books
    - docker2/media/downloads/comics
    - docker2/media/downloads/kids
    - docker2/media/downloads/movies
    - docker2/media/downloads/music
    - docker2/media/downloads/tv
  tags: sabnzbd

- name: Ensure Sabnzbd Dataset Exist
  when: inventory_hostname == groups['media'][0]
  community.general.zfs:
    name: docker2/apps/sabnzbd
    state: present
  tags: sabnzbd

- name: Ensure Sabnzbd Configuration Files Exist
  when: inventory_hostname == groups['media'][0]
  template:
    src: sabnzbd.ini.j2
    dest: "{{project_root_directory}}/sabnzbd/sabnzbd.ini"
  tags: sabnzbd
  no_log: true

- name: Deploy Sabnzbd Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: sabnzbd
    hostname: "{{sabnzbd_hostname}}"
    image: "{{sabnzbd_docker_image}}:{{sabnzbd_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: yes
    restart_config:
      condition: on-failure
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      TZ: "{{default_timezone}}"
      DOCKER_MODS: "gilbn/theme.park:sabnzbd"
      TP_THEME: "{{theme_park_default}}"
    placement:
      constraints:
        - node.id == {{docker2_node_id}}
    replicas: 1
    mounts:
      - source: "/datavol/apps/sabnzbd/"
        target: /config/
        type: bind
      - source: "{{project_download_directory}}"
        target: /media/downloads/
        type: bind
      - source: "{{project_download_directory}}/incomplete/"
        target: /media/downloads/incomplete/
        type: bind
    labels:
      traefik.http.routers.sabnzbd.entrypoints: "websecure"
      traefik.http.routers.sabnzbd.rule: "Host(`sabnzbd.{{project_tld}}`)"
      traefik.http.routers.sabnzbd.middlewares: "default-headers@file,authelia@file"
      traefik.http.routers.sabnzbd.tls: "true"
      traefik.http.routers.sabnzbd.service: "sabnzbd"
      traefik.http.routers.sabnzbd.tls.certresolver: "{{default_certificate_resolver}}"
      traefik.http.services.sabnzbd.loadbalancer.server.port: "{{sabnzbd_port}}"
      traefik.enable: "true"
    state: present
  tags: sabnzbd