---
- name: Ensure Ombi Dataset Exist
  when: inventory_hostname == groups['media'][0]
  file:
    name: "{{project_root_directory}}/ombi"
    state: directory
  tags: ombi

- name: Deploy Ombi Service
  when: inventory_hostname == groups['managers'][0]
  community.docker.docker_swarm_service:
    name: ombi
    hostname: "{{ombi_hostname}}"
    image: "{{ombi_docker_image}}:{{ombi_version}}"
    networks:
      - "{{traefik_network}}"
    mode: replicated
    force_update: false
    restart_config:
      condition: on-failure
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      TZ: "{{default_timezone}}"
    placement:
      constraints:
        - node.id == {{docker_worker2_node_id}}
    replicas: 1
    mounts:
      - source: "{{project_root_directory}}/ombi/"
        target: /config
        type: bind
    labels:
      traefik.http.routers.ombi.entrypoints: "websecure"
      traefik.http.routers.ombi.rule: "Host(`ombi.{{project_tld}}`)"
      traefik.http.routers.ombi.middlewares: "default-headers@file,authelia@file"
      traefik.http.routers.ombi.tls: "true"
      traefik.http.routers.ombi.service: "ombi"
      # traefik.http.routers.ombi.tls.certresolver: "{{default_certificate_resolver}}" # Un-Comment this line to use a rule-based cert
      traefik.http.services.ombi.loadbalancer.server.port: "{{ombi_port}}"
      traefik.enable: "true"
    state: present
  tags: ombi