---
sonarr_version: "4.0.5.1710-ls240"
sonarr_hostname: "sonarr"
sonarr_docker_image: "ghcr.io/linuxserver/sonarr"
sonarr_anime_version: "latest"
sonarr_anime_hostname: "4.0.5.1710-ls240"
sonarr_anime_docker_image: "ghcr.io/linuxserver/sonarr"