---
immich_version: "latest"
immich_database_version: "pg14-v0.3.0"
immich_hostname: "immich_server"
immich_machine_learning_hostname: "immich_machine_learning"
#immich_redis_hostname: "immich_redis"
immich_database_hostname: "immich_postgres"
immich_docker_image: "ghcr.io/immich-app/immich-server"
immich_machine_learning_image: "ghcr.io/immich-app/immich-machine-learning"
#immich_redis_image: "redis"
immich_database_docker_image: "tensorchord/pgvecto-rs"
immich_port: "2283"
immich_database_port: "5432"
